# Introduction
For our final project, we have decided to enter the AWS x NFL Annual Big Data Bowl – a competition hosted on Kaggle where participants are challenged to find meaningful insights from week-to-week game data within the 2023 NFL season, creating and delivering a compelling story within the data. The competition has 2 tracks, including a University Track – the one we entered into, tasked with analyzing player movement, creating player or team metrics for either the offensive or defensive units, and/or evaluating other passing play topics.

As a part of this competition, we will be creating models and various types of visualizations of both model outputs, as well as the raw data itself.

We chose to work on this topic because we both are passionate fans of the Philadelphia Eagles and Detroit Lions, and in particular, enjoy the advanced analytic insights that AWS provides to viewers during football games. As avid fans, developing and contributing something used in practice by professional teams would be a massive accomplishment, and we are eager to put our combined domain knowledge and technical backgrounds together to deliver something that is both unique and insightful.
